service: buyer
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: test
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
functions:
  buy:
    handler: index.handler
    events:
      - schedule: rate(7 days)
    environment:
      BUYER_CB_USE_SANDBOX: true
