service: buyer
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: test
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
functions:
  buy:
    handler: handler.buy
    events:
      - http:
          path: /buy
          method: post
          authorizer:
            type: aws_iam
      - schedule: rate(1 day)
    environment:
      BUYER_CB_USE_SANDBOX: true
